fixtures:
  # repositories:
    # stdlib:          "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    # tomcat:          "https://github.com/puppetlabs/puppetlabs-tomcat.git"
    # apt:             "https://github.com/puppetlabs/puppetlabs-apt.git"
    # epel:            "https://github.com/stahnma/puppet-module-epel.git"
    # docker_platform: "https://github.com/puppetlabs/puppetlabs-docker_platform.git"
    # docker:          "https://github.com/garethr/garethr-docker.git"
  symlinks:
    docker_tomcat_module: "#{source_dir}"

  forge_modules:
    cis_harden_tomcat:
      repo: autostructure-cis_harden_tomcat
      ref: 0.1.4
    java:
      repo: puppetlabs-java
      ref: 2.1.0
    tomcat:
      repo: puppetlabs-tomcat
      ref: 2.0.0
    stdlib:
      repo: puppetlabs-stdlib
      ref: 4.20.0
    concat:
      repo: puppetlabs-concat
      ref: 4.0.1
    staging:
      repo: puppet-staging
      ref: 2.2.0
    archive:
      repo: puppet-archive
      ref: 1.3.0
